### ISSUE TITLE
Minor Bug Fixes for Level and pSprite

### ISSUE THREAD

**Issue by Pencraft** [WeAreDMVR/FixEverything#9]
Level does not properly add cocos2d::sprite's from objects to the Scene via addChild().
Also, pSprite::setPosition() does not set the position of the underlying sprite by calling cocos2d::Sprite::setPosition().

**Comment by lppham** [comment]
(this is patrick) The push_back function used in createFixtures to append sprites has to make a full copy of the sprite. So we have to implement the copy constructor pSprite(const pSprite& obj)

**Comment by Pencraft** [comment]
What's the best way to save just pSprite pointers? I don't think we want to be making multiple copies of every sprite -- much harder to clean up and update

**Comment by lppham** [comment]
this is probably a Lee question :/
